# Default values for podinfo.

replicaCount: 1
logLevel: info
host: #0.0.0.0
backend: #http://backend-podinfo:9898/echo
backends: []

udl:
  url: "https://test.udl.com"
  send: "false"
  receive: "false"
instance:
  name: "Example - Change Me"
  tail: "77187"
  mws: "C017A"

custom-dns:
  enabled: false
  server: 192.168.16.250

apps:
  enabled: false
  nimbus-rush: false 
  podinfo:
    enabled: false
  c2d2:
    enabled: false
  demeter:
    enabled: false
  levels:
    enabled: false