apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: aoa
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://sync.git.mil/maf/infrastructure/nucleus/argo-apps.git
        path: argocd/dev
        targetRevision: main
        directory:
            recurse: true
            jsonnet: {}
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true