{{- if .Values.apps.enabled }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: atoms-jumpstart
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./jumpstart
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
{{- end }}