# 1. Query your secret for "existance" and return in the $secret variable
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "sops-gpg") -}}

# 2. If the secret exists, write it back out (it'll be Base64 encoded so used the "data" key)
{{ if $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: sops-gpg
type: Opaque


data: {{ $secret.data }}

{{ end }}