{{ if .Values.apps.enabled -}}
{{ if .Values.apps.c2d2.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c2d2-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: c2d2-dev
    name: in-cluster
  project: atoms-project
  source:
    path: ./apps/c2d2
    repoURL: https://sync.git.mil/maf/infrastructure/nucleus/argo-apps.git
    targetRevision: pkg
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
{{- end }}
{{- end }}
# ---
# {{ if .Values.apps.enabled -}}
# {{ if .Values.apps.c2d2.enabled -}}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     name: atoms-c2d2-env
#     namespace: argocd
# data:
#   UDL_URL: "{{ .Values.apps.c2d2.udl.url }}"
#   UDL_SEND: "{{ .Values.apps.c2d2.udl.send }}"
#   UDL_RECEIVE: "{{ .Values.apps.c2d2.udl.receive }}"
#   ATOMS_NAME: "{{ .Values.apps.c2d2.instance.name }}"
#   TAIL_NUM: "{{ .Values.apps.c2d2.instance.tail }}"
#   MWS: "{{ .Values.apps.c2d2.instance.mws }}"

# {{- end }}
# {{- end }}
