{{ if .Values.apps.enabled -}}
{{ if .Values.apps.levels.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: levels-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: c2d2-dev
    name: in-cluster
  project: appbundle-project
  source:
    path: ./apps/levels
    repoURL: https://sync.git.mil/maf/infrastructure/nucleus/argo-apps.git
    targetRevision: pkg
  syncPolicy:
                automated:
                  prune: true
                  selfHeal: true

{{- end }}
{{- end }}

